
version: '2'

services:
  etcd:
    container_name: etcd
    image: docker.io/bitnami/etcd:3.5
    networks:
      - alimama
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes

  node1:
    container_name: node-1
    image: public-images-registry-vpc.cn-hangzhou.cr.aliyuncs.com/demo/alimama-2023:B-v0
    cpuset: "1-16"
    deploy:
      resources:
        limits:
          cpus: '16.0'
          memory: 16G 
        reservations:
          cpus: '16.0'
          memory: 16G
    networks:
      - alimama
    volumes:
      - "./node-1:/work"
      - "./data:/data:ro"
    environment:
      - NODE_ID=1
      - NODE_NUM=3
      - MEMORY=16G
      - CPU=16C

    depends_on:
      - etcd
      - testbench
    working_dir: /work
    command: ["./run.sh"]

  node2:
    container_name: node-2
    image: public-images-registry-vpc.cn-hangzhou.cr.aliyuncs.com/demo/alimama-2023:B-v0
    cpuset: "17-32"
    deploy:
      resources:
        limits:
          cpus: '16.0'
          memory: 16G 
        reservations:
          cpus: '16.0'
          memory: 16G
    networks:
      - alimama
    volumes:
      - "./node-2:/work"
      - "./data:/data:ro"
    environment:
      - NODE_ID=2
      - NODE_NUM=3
      - MEMORY=16G
      - CPU=16C
    depends_on:
      - etcd
      - testbench
    working_dir: /work/
    command: ["./run.sh"]

  node3:
    container_name: node-3
    image: public-images-registry-vpc.cn-hangzhou.cr.aliyuncs.com/demo/alimama-2023:B-v0
    cpuset: "33-48"
    deploy:
      resources:
        limits:
          cpus: '16.0'
          memory: 16G 
        reservations:
          cpus: '16.0'
          memory: 16G
    networks:
      - alimama
    volumes:
      - "./node-3:/work"
      - "./data:/data:ro"
    environment:
      - NODE_ID=3
      - NODE_NUM=3
      - MEMORY=16G
      - CPU=16C
    depends_on:
      - etcd
      - testbench
    working_dir: /work/
    command: ["./run.sh"]

  testbench:
    container_name: node-testbench
    image: public-images-registry-vpc.cn-hangzhou.cr.aliyuncs.com/demo/alimama-2023:B-v0
    deploy:
      resources:
        limits:
          cpus: '16.0'
          memory: 16G 
        reservations:
          cpus: '16.0'
          memory: 16G
    networks:
      - alimama
    depends_on:
      - etcd
    volumes:
      - "./testbench:/work"
      - "./data:/data:ro"
    working_dir: /work
    command: ["bash", "./run.sh"]
networks:
  alimama:
    name: alimama_2023_B_alimama
    internal: true
    external: false

