
version: '2'

services:
  etcd:
    container_name: alimama_2023_B_etcd
    image: docker.io/bitnami/etcd:3.5
    networks:
      - alimama
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes

  node1:
    container_name: alimama_2023_B_node-1
    image: public-images-registry.cn-hangzhou.cr.aliyuncs.com/demo/alimama-2023:v0
    cpuset: "1"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G 
        reservations:
          cpus: '1.0'
          memory: 2G
    networks:
      - alimama
    volumes:
      - "./node-1:/work"
      - "./data:/data:ro"
    environment:
      - NODE_ID=1
      - MEMORY=16G
      - CPU=2C

    depends_on:
      - etcd
    working_dir: /work/build
    command: ["bash", "./run.sh", "node-1"]

  node2:
    container_name: alimama_2023_B_node-2
    image: public-images-registry.cn-hangzhou.cr.aliyuncs.com/demo/alimama-2023:v0
    cpuset: "2"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G 
        reservations:
          cpus: '1.0'
          memory: 2G
    networks:
      - alimama
    volumes:
      - "./node-2:/work"
      - "./data:/data:ro"
    environment:
      - NODE_ID=2
      - MEMORY=16G
      - CPU=2C
    depends_on:
      - etcd
    working_dir: /work/build
    command: ["bash", "./run.sh", "node-2"]

  node3:
    container_name: alimama_2023_B_node-3
    image: public-images-registry.cn-hangzhou.cr.aliyuncs.com/demo/alimama-2023:v0
    cpuset: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G 
        reservations:
          cpus: '1.0'
          memory: 2G
    networks:
      - alimama
    volumes:
      - "./node-3:/work"
      - "./data:/data:ro"
    environment:
      - NODE_ID=3
      - MEMORY=16G
      - CPU=2C
    depends_on:
      - etcd
    working_dir: /work/build
    command: ["bash", "./run.sh", "node-3"]

  testbench:
    container_name: alimama_2023_B_node-testbench
    image: public-images-registry.cn-hangzhou.cr.aliyuncs.com/demo/alimama-2023:v0
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 8G 
        reservations:
          cpus: '8.0'
          memory: 8G
    networks:
      - alimama
    depends_on:
      - etcd
      - node1
      - node2
      - node3
    links:
      - docker-proxy #可以通过 http 和 grpc 获取各个节点的 cpu 和内存，start 和 stop 节点，接口未实现；可以先看 cpu 和内存的日志
    volumes:
      - "./testbench:/work"
      - "./data:/data:ro"
      - "./docker-proxy/logs:/logs/docker-proxy"
    working_dir: /work
    command: ["bash", "./run.sh"]

  docker-proxy:
    container_name: alimama_2023_B_docker-proxy
    image: public-images-registry.cn-hangzhou.cr.aliyuncs.com/demo/alimama-2023:v0
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G 
        reservations:
          cpus: '1.0'
          memory: 2G
    networks:
      - alimama
    depends_on:
      - etcd
      - node1
      - node2
      - node3
    volumes:
      - "./docker-proxy:/work"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: /work
    command: ["./docker-proxy", "-containers", "node-1,node-2,node-3"]


networks:
  alimama:
    name: alimama_2023_B_alimama
    internal: true
    external: false

