time ./client --mode 1 --req_file /data/test_case2.csv --res_file a0.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a1.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a2.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a3.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a4.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a5.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a6.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a7.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a8.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a9.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a10.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a11.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a0.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a1.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a2.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a3.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a4.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a5.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a6.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a7.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a8.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a9.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a10.csv&
time ./client --mode 1 --req_file /data/test_case2.csv --res_file a11.csv&
